### ISSUE TITLE
Why not merge to SpinalHDL?

### ISSUE THREAD

**Issue by volatile-static** [PulseRain/SpinalHDL_lib#1]
https://github.com/PulseRain/SpinalHDL_lib/blob/b9f2784616d0e2779d9271c5291b85a2058e9018/common/bundle_utils.scala
That's a great idea. Maybe it's needed by many users. So I suggest that submit a pull request to SpinalHDL/dev.

**Comment by PulseRainmaker** [comment]
Thanks for your suggestion! We are preparing a document for this and will submit a PR soon.

**Comment by volatile-static** [comment]
Looking forward to your PR!

**Comment by PulseRainmaker** [comment]
Thanks for your interest in our library. After reviewing, we think those functions already have their counterparts in the SpinalHDL core.

get_total_bundle_bits <=> .getBitsWidth
bundle_to_bits           <=> .asBits
bits_to_bundle           <=> .assignFromBits

However, the .assignFromBits was not explicitly mentioned in the old documentation for Bundle. So instead of reinventing the wheels, we submitted a PR to the SpinalDoc-RTD, and got accepted. 

The updated Bundle doc is at
[https://spinalhdl.github.io/SpinalDoc-RTD/SpinalHDL/Data%20types/bundle.html](https://spinalhdl.github.io/SpinalDoc-RTD/SpinalHDL/Data%20types/bundle.html)

See the section "Convert Bits back to Bundle"

Thanks!

**Comment by volatile-static** [comment]
Thank you very much!
